### ISSUE TITLE
Intermittent InvalidOperationException: The collection argument is empty and has been marked as complete with regards to additions

### ISSUE THREAD

**Issue by duncanawoods** [daveaglick/Buildalyzer#141]
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (The collection argument is empty and has been marked as complete with regards to additions.)) (The collection argument is empty and has been marked as complete with regards to additions.)
  ----> System.InvalidOperationException : The collection argument is empty and has been marked as complete with regards to additions.
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.WhereQueryOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Buildalyzer.Workspaces.AnalyzerManagerExtensions.GetWorkspace(AnalyzerManager manager) in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs:line 13
   at CallGraph.Grapher.Parse(String solutionFile, String projectName) in /home/duncan/Projects/snug/tools/CallGraph/src/CallGraph/Grapher.cs:line 18
   at CallGraphTest.TestParsing.test_lush() in /home/duncan/Projects/snug/tools/CallGraph/src/CallGraphTest/TestParsing.cs:line 283
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
--InvalidOperationException
   at System.Collections.Concurrent.BlockingCollection`1.Take()
   at MsBuildPipeLogger.PipeBuffer.TakeBuffer()
   at MsBuildPipeLogger.PipeBuffer.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.ReadString()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadString()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadStringDictionary()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadPropertyList()
   at Microsoft.Build.Logging.BuildEventArgsReader.ReadProjectStartedEventArgs()
   at Microsoft.Build.Logging.BuildEventArgsReader.Read()
   at MsBuildPipeLogger.BuildEventArgsReaderProxy.Read()
   at MsBuildPipeLogger.PipeLoggerServer`1.Read()
   at MsBuildPipeLogger.PipeLoggerServer`1.ReadAll()
   at Buildalyzer.ProjectAnalyzer.BuildTargets(BuildEnvironment buildEnvironment, String targetFramework, String[] targetsToBuild, AnalyzerResults results) in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer/ProjectAnalyzer.cs:line 225
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, BuildEnvironment buildEnvironment) in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer/ProjectAnalyzer.cs:line 183
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework) in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer/ProjectAnalyzer.cs:line 161
   at Buildalyzer.ProjectAnalyzer.Build() in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer/ProjectAnalyzer.cs:line 193
   at Buildalyzer.Workspaces.AnalyzerManagerExtensions.<>c.<GetWorkspace>b__0_0(ProjectAnalyzer p) in /home/duncan/Projects/snug/forks/Buildalyzer/Buildalyzer.Workspaces/AnalyzerManagerExtensions.cs:line 15
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by duncanawoods** [comment]
It is thrown in `PipeBuffer.cs` from MsBuildPipeLogger here:

``` csharp
        private bool TakeBuffer()
        {
            if (_current == null)
            {
                if (_queue.IsCompleted)
                {
                    return false;
                }
                _current = _queue.Take();
            }
            return true;
        }
```

It sounds like `_queue` is empty so `Take` throws. My concern about just adding an `IsEmpty` check is that there maybe thread safety issues.

**Comment by duncanawoods** [comment]
This maybe related to the thread safety issues in daveaglick/Buildalyzer#138 and  daveaglick/Buildalyzer#134

**Comment by duncanawoods** [comment]
Ok so `_queue.IsCompleted` includes a test of empty so that means there is a race condition between `_queue.IsCompleted` and `_queue.Take()`.

There is a `TryTake` method which should probably be used in a multithreaded context but `_queue` is accessed from multiple public methods so it won't be sufficient. I am trying putting synchronization locks around it.

**Comment by duncanawoods** [comment]
Not much luck

- Can't synchronise access to the queue because it has blocking calls so it will deadlock
- Weird... `TryTake` crashes my nunit test runner with `Cannot access a closed pipe`

**Comment by duncanawoods** [comment]
Looking at the [BlockingCollection documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.take?view=netcore-3.1), it seems this exception is to be expected and not an error condition that should be allowed to bubble up.

I'd suggest replacing this:

``` csharp
private bool TakeBuffer()
{
    if (_current == null)
    {
        if (_queue.IsCompleted) // <--- RACE CONDITION
        {
            return false;
        }
        _current = _queue.Take(); // <---
    }
    return true;
}
```

with 

``` csharp
private bool TakeBuffer()
{
    if (_current == null)
    {
        // Take() can throw when marked as complete from another thread
        // https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.take?view=netcore-3.1
        try
        {
            this._current = _queue.Take();
        }
        catch (ObjectDisposedException)
        {
            return false;
        }
        catch (OperationCanceledException)
        {   
            return false;
        }
        catch (InvalidOperationException)
        {   
            return false;
        }
    }
    return true;
}
```
