### ISSUE TITLE
Error in project compilation if dotnet-core-sdk 2.1 is used.

### ISSUE THREAD

**Issue by itn3000** [daveaglick/Buildalyzer#32]
# Steps to reproduce

## Environment

here is my `dotnet --info` result

```
.NET コマンド ライン ツール (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.3

  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

## Steps

1. create AnalyzerManager instance
2. get ProjectAnalyzer with AnalyzerManager.GetProject for project which was created by `dotnet new console`
3. get ProjectInstance with ProjectAnalyer().GetProject

# Expected behavior

get ProjectInstance

# Actual Behavior

I got following exception
```
Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[MSBuild]::IsRunningFromVisualStudio()". [MSBuild]::IsRunningFromVisualStudio Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files\dotnet\sdk\2.1.2\Microsoft.Common.CurrentVersion.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.ConditionEvaluator.ConditionEvaluationState`2.ExpandIntoStringBreakEarly(String expression)
   at Microsoft.Build.Evaluation.StringExpressionNode.EvaluatesToEmpty(IConditionEvaluationState state)
   at Microsoft.Build.Evaluation.MultipleComparisonNode.BoolEvaluate(IConditionEvaluationState state)
   at Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[P,I](String condition, ParserOptions options, Expander`2 expander, ExpanderOptions expanderOptions, Dictionary`2 conditionedPropertiesTable, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, ProjectRootElementCache projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateConditionCollectingConditionedProperties(ProjectElement element, String condition, ExpanderOptions expanderOptions, ParserOptions parserOptions, ProjectRootElementCache projectRootElementCache)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Buildalyzer.ProjectAnalyzer.Load()
   at Buildalyzer.ProjectAnalyzer.Compile()
   at buildalyzertest.Program.Main(String[] args) in G:\src\gitrepos\dotnet-sandbox\buildalyzer-error-with-core-sdk-2.1\buildalyzertest\Program.cs:line 15
```

# Notes

This can be avoided by adding the following package in project which uses Buildalyzer.

* Microsoft.Build, Version=15.5.180
* Microsoft.Build.Tasks.Core, Version=15.5.180
* Microsoft.Build.Utilities.Core, Version=15.5.180

or by putting [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) which specifies sdk/version = `2.0.x` on processed csproj.(requires dotnet-sdk 2.0)

**Comment by itn3000** [comment]
I think it depends on tool's path which is specified in Microsoft.Build.Evaluation.Toolset?

**Comment by ReubenBond** [comment]
I'm hitting this, too. I'm not sure the issue, but I saw these other threads which seem related: https://github.com/Microsoft/msbuild/issues/2775 https://github.com/dotnet/docfx/issues/2265

**Comment by stofte** [comment]
Yeah, this is something that broke in MSBuild. I was using 2.1 just last week, and when I open the project now, it's broken. Thanks alot for fixes @itn3000

**Comment by kentcb** [comment]
Hit this as well. I tried repairing my installation according some advice I read [here](https://github.com/Microsoft/msbuild/issues/2775), but to no avail. Adding a dependency on the packages mentioned by @itn3000 worked for me, too.

**Comment by daveaglick** [comment]
I’m also hitting this in AppVeyor now. Buildalyzer currently links to the 15.3.409 MSBuild packages. Hopefully linking to 15.5.180 directly in Buildalyzer will resolve this. I’ll try to get a new release out today or tomorrow.
