### ISSUE TITLE
Properties like MSBuildThisFileDirectory don't work

### ISSUE THREAD

**Issue by dfederm** [daveaglick/Buildalyzer#43]
Because of an MSBuild bug (Microsoft/msbuild#3030) and the fact that Buildalyzer loads using an `XmlReader` instead of using a file name, properties like `MSBuildThisFileDirectory` used during project load don't work.

Minimal repro:
```
<Project ToolsVersion="15.0">
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), Directory.Build.props))\Directory.Build.props" />
  <Target Name="Build" />
</Project>
```

I get the error:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The expression "[MSBuild]::GetDirectoryNameOfFileAbove('', Directory.Build.props)" cannot be evaluated. The path is not of a legal form.
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(XmlReader xmlReader)
   at Buildalyzer.ProjectAnalyzer.Load()
```

Consider loading by filename when no "ProjectTweaker" is provided, even though it requires a whole new load of the Xml which you've already done, at least until MsBuild provides a solution itself.

**Comment by dfederm** [comment]
@daveaglick You're right that Buildalyzer attempts to set the FullFilePath, and I suspect a re-evaluate after setting that may populate these properties, but that happens after the initial load. If the initial load requires these properties (ie. used in Imports), loading may fail.

**Comment by daveaglick** [comment]
Ah, think I got it - so we’ve got to get those set during initial load and not via evaluation sometime later. I’d still like to find a way to do this via a stream instead of the file system - hopefully there’s way.

**Comment by jirikopecky** [comment]
@daveaglick I have created a pull request that should address this issue: #45, could you please take a look? The solution is taken from Roslyn MSBuildWorkspace and related classes and utilizes project creation through ProjectRootElement class.

**Comment by daveaglick** [comment]
@jirikopecky Thanks! I took a quick glance at the PR the other day and it looked good. I'll take a closer look and merge it in hopefully next week. Also have a couple other things to get in (plus a new MSBuild API) so I'll probably do a release with these changes next week too.
