### ISSUE TITLE
Investigate failures on AppVeyor

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Buildalyzer#48]
I'm seeing some odd build failures when using (not building) Buildalyzer on AppVeyor. I _think_ I've got a handle on what's going on, but want to get some notes down heading into the weekend.

The error I started seeing was this:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files\dotnet\sdk\2.1.103\Microsoft.Common.CrossTargeting.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1](IElementLocation elementLocation, String resourceName, T1 arg0)
...
```

If you look at "Microsoft.Common.CrossTargeting.targets" it contains:
```
<!--
    This will import NuGet restore targets. We need restore to work before any package assets are available.
  -->
  <PropertyGroup>
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'=='' and '$([MSBuild]::IsRunningFromVisualStudio())'=='true'">$(MSBuildToolsPath32)\..\..\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</NuGetRestoreTargets>
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildToolsPath)\NuGet.targets</NuGetRestoreTargets>
  </PropertyGroup>

  <Import Project="$(NuGetRestoreTargets)" />
-->
```

So it appears that the intrinsic method `IsRunningFromVisualStudio()` is `true` which causes us to pick the first branch, except the property `MSBuildToolsPath32` is empty so we end up at the root before looking for the "NuGet.targets" file in the wrong place. [That method](https://github.com/Microsoft/msbuild/blob/7d6ee54465fc8236f681cc61a169273bb9374291/src/Build/Evaluation/IntrinsicFunctions.cs#L487) just checks the mode from `BuildEnvironmentHelper` which gets set [here](https://github.com/Microsoft/msbuild/blob/7d6ee54465fc8236f681cc61a169273bb9374291/src/Shared/BuildEnvironmentHelper.cs#L74).

My best guess is that AppVeyor either sets the "VSINSTALLDIR" or "VisualStudioVersion" environment variable which causes `BuildEnvironmentHelper` to determine we're running from Visual Studio [here](https://github.com/Microsoft/msbuild/blob/7d6ee54465fc8236f681cc61a169273bb9374291/src/Shared/BuildEnvironmentHelper.cs#L219) even though we're not.

We need to fail the VS test and instead pick the "NuGet.targets" file off the `MSBuildToolsPath` property. A couple thoughts:
* Could figure out which of the two envionment variables is set in AppVeyor and unset them in the `AppVeyor.yml` file - that would help me but not the general case
* Could unset both of these when running Buildalyzer and then set them back afterwards
* Could short-circuit the whole thing by setting "MSBUILD_EXE_PATH" (see [here](https://github.com/Microsoft/msbuild/blob/7d6ee54465fc8236f681cc61a169273bb9374291/src/Shared/BuildEnvironmentHelper.cs#L122)) (leaning towards this option - it's also what [DocFx does](https://github.com/dotnet/docfx/blob/916929a58c92afd1bb85689f53f56763771a86fa/src/Microsoft.DocAsCode.Metadata.ManagedReference/EnvironmentHelper.cs#L143)).

**Comment by daveaglick** [comment]
Related to #42
