### ISSUE TITLE
.NET Framework builds failing in GetAssemblyVersion task

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Buildalyzer#56]
Builds are failing for .NET Framework projects:

```
Project "E:\Code\Buildalyzer\tests\projects\SdkFrameworkProject\SdkFrameworkProject.csproj" (Compile target(s)):

Target ResolveAssemblyReferences:
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3088: Could not read state file "obj\Debug\net462\SdkFrameworkProject.csprojAssemblyReference.cache". Exception has been thrown by the target of an invocation.
Done building target "ResolveAssemblyReferences" in project "SdkFrameworkProject.csproj".
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target ResolveCodeAnalysisRuleSet:
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "ManagedMinimumRules.ruleset".
Done building target "ResolveCodeAnalysisRuleSet" in project "SdkFrameworkProject.csproj".
Target GetAssemblyVersion:
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: The "GetAssemblyVersion" task failed unexpectedly.
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Done building target "GetAssemblyVersion" in project "SdkFrameworkProject.csproj" -- FAILED.

Done building project "SdkFrameworkProject.csproj" -- FAILED.

Build FAILED.
```

I'm still not totally sure why this target is having problems, but after some research it looks like we can turn off the `ResolveAssemblyReference` cache with the property `DisableRarCache` (see https://github.com/Microsoft/msbuild/commit/331cd4a4042be80064e4a89811b23771e6b09409) and that seems to fix the issue. This is also apparently what VS does for design-time builds. I suspect it has something to do with the way the RAR cache file name is generated, but not going to spend more time on it.

**Comment by daveaglick** [comment]
This is resolved in the most recent commit.
